### PR TITLE
Allow transformers-0.6

### PR DESCRIPTION
**Pull request by Bodigrim**
Cf. https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9370
CC @bgamari

### CODE REVIEW

**Comment by Bodigrim** [comment]
@bgamari just a gentle reminder to review.

**Comment by Bodigrim** [comment]
@bgamari another ping. This is blocking https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9370.

**Comment by bgamari** [comment]
Thanks @Bodigrim.

**Comment by andreasabel** [comment]
Presumably fixes:
- #165

**Comment by sjakobi** [comment]
I have used my Hackage trustee powers to create a matching Hackage revision: https://hackage.haskell.org/package/haskeline-0.8.2/revisions/

**Pull request merged**
