### PR TITLE
Bump base upper bound

### PR DESCRIPTION
**Pull request by bgamari**
For GHC 9.4

### CODE REVIEW

**Comment by bgamari** [comment]
@judah, ping.

**Comment by bgamari** [comment]
@judah, can we merge this? This will very shortly be blocking the 9.4.1 release.

**Comment by bgamari** [comment]
@judah, ping.

Alternatively, do feel free to grant me rights to this repository and the Hackage package and I would be happy to manage this myself.

**Comment by fluesvamp** [comment]
don't know if the Changelog should be updated

anyways, here's some typo fixes from closed PR

```
sed -i "s/accomodate/accommodate/g" haskeline/Changelog
sed -i "s/cant/can't/g" haskeline/System/Console/Haskeline/Backend/Win32.hsc
sed -i "s/contrast/contrast/g" haskeline/System/Console/Haskeline/IO.hs
sed -i "s/mimicing/mimicking/g" haskeline/System/Console/Haskeline/Vi.hs
sed -i "s/superceded/superseded/g" haskeline/System/Console/Haskeline/Backend/Posix.hsc
```

**Comment by bgamari** [comment]
Thanks @fluesvamp! However, do note that both "supercede" and "supersede" appear to be correct.

**Pull request merged**
